---
- name: configure a webserver
  hosts: webservers
  remote_user: myuser
  become: yes

  roles:
    - common
    - web

- name: configure haproxy
  hosts: haproxyserver
  remote_user: myuser
  become: yes

  roles:
    - common
    - haproxy
